# Generated by Django 5.2.8 on 2026-03-19 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Translation History', 'verbose_name_plural': 'Translation Histories'},
        ),
        migrations.AddField(
            model_name='translationhistory',
            name='translation_type',
            field=models.CharField(choices=[('text_to_gloss', 'Text to Gloss'), ('speech_to_gloss', 'Speech to Gloss'), ('gloss_to_text', 'Gloss to Text')], default='text_to_gloss', max_length=20),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='input_text',
            field=models.TextField(help_text='Original input text'),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='output_text',
            field=models.TextField(help_text='Translated output'),
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.translationhistory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
