# Generated by Django 4.2.7 on 2026-03-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_translationhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional feedback comment'),
        ),
        migrations.AddIndex(
            model_name='translationhistory',
            index=models.Index(fields=['created_at'], name='api_transla_created_f8953d_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['created_at'], name='api_userfee_created_3a264d_idx'),
        ),
    ]
